Sys.setenv(http_proxy =  "www-proxy.us.oracle.com:80" , https_proxy =  "www-proxy.us.oracle.com:80")
Sys.unsetenv("http_proxy")
Sys.unsetenv("https_proxy")
Sys.getenv("http_proxy")
Sys.getenv("https_proxy")
getwd()
install.packages("MASS")
library(MASS)
input.data <- Cars93
head(input.data)
head(input.data , 10)
tail(input.data)
tail(input.data, -10)
str(input.data)
summary(input.data, 10)